/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation

public enum solana_todoError: String, Error {
    /**
 * ContentTooLong: '0x1770'
 *
 * @category Errors
 * @category generated
 */
    case contentTooLongError = "0x1770"

    public var code: String? { self.rawValue }
}

extension solana_todoError: LocalizedError {
    public var errorDescription: String? {
        switch self {
            /**
 * ContentTooLong: 'The provided topic should be 300 characters long maximum.'
 *
 * @category Errors
 * @category generated
 */
    case .contentTooLongError: return "The provided topic should be 300 characters long maximum."
        }
    }
}