[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_todo = "AaCX2J9gPgujGg5xsNhvPuziJpQvWoXd5HrQj26c2ep3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tsv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
